Full context diffs with anotations

diff --git a/affected_commits/xz/2c189bb00af73dc7ba1a67a9d274d5be03ee3a88/patches/2c189bb00af73dc7ba1a67a9d274d5be03ee3a88.diff b/affected_commits/xz/2c189bb00af73dc7ba1a67a9d274d5be03ee3a88/patches/2c189bb00af73dc7ba1a67a9d274d5be03ee3a88.diff
--- a/affected_commits/xz/2c189bb00af73dc7ba1a67a9d274d5be03ee3a88/patches/2c189bb00af73dc7ba1a67a9d274d5be03ee3a88.diff
+++ b/affected_commits/xz/2c189bb00af73dc7ba1a67a9d274d5be03ee3a88/patches/2c189bb00af73dc7ba1a67a9d274d5be03ee3a88.diff
@@ -18,7 +18,136 @@ diff --git a/tests/test_compress.sh b/tests/test_compress.sh
 index 61d20ce9..0aa81001 100755
 --- a/tests/test_compress.sh
 +++ b/tests/test_compress.sh
-@@ -130,8 +130,8 @@ test_xz -4
+@@ -1,149 +1,149 @@
+ #!/bin/sh
+ 
+ ###############################################################################
+ #
+ # Author: Lasse Collin
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ ###############################################################################
+ 
+ # If xz wasn't built, this test is skipped.
+ if test -x ../src/xz/xz ; then
+ 	:
+ else
+ 	exit 77
+ fi
+ 
+ # If compression or decompression support is missing, this test is skipped.
+ # This isn't perfect as if only some compressors or decompressors are disabled
+ # then this script can still fail because for now this doesn't check the
+ # availability of each filter.
+ if grep 'define HAVE_ENCODERS' ../config.h > /dev/null \
+ 		&& grep 'define HAVE_DECODERS' ../config.h > /dev/null ; then
+ 	:
+ else
+ 	echo "Compression or decompression support is disabled, skipping this test."
+ 	exit 77
+ fi
+ 
+ # Find out if our shell supports functions.
+ eval 'unset foo ; foo() { return 42; } ; foo'
+ if test $? != 42 ; then
+ 	echo "/bin/sh doesn't support functions, skipping this test."
+ 	exit 77
+ fi
+ 
+ test_xz() {
+ 	if $XZ -c "$@" "$FILE" > "$TMP_COMP"; then
+ 		:
+ 	else
+ 		echo "Compressing failed: $* $FILE"
+ 		exit 1
+ 	fi
+ 
+ 	if $XZ -cd "$TMP_COMP" > "$TMP_UNCOMP" ; then
+ 		:
+ 	else
+ 		echo "Decompressing failed: $* $FILE"
+ 		exit 1
+ 	fi
+ 
+ 	if cmp "$TMP_UNCOMP" "$FILE" ; then
+ 		:
+ 	else
+ 		echo "Decompressed file does not match" \
+ 				"the original: $* $FILE"
+ 		exit 1
+ 	fi
+ 
+ 	if test -n "$XZDEC" ; then
+ 		if $XZDEC "$TMP_COMP" > "$TMP_UNCOMP" ; then
+ 			:
+ 		else
+ 			echo "Decompressing failed: $* $FILE"
+ 			exit 1
+ 		fi
+ 
+ 		if cmp "$TMP_UNCOMP" "$FILE" ; then
+ 			:
+ 		else
+ 			echo "Decompressed file does not match" \
+ 					"the original: $* $FILE"
+ 			exit 1
+ 		fi
+ 	fi
+ }
+ 
+ XZ="../src/xz/xz --memlimit-compress=48MiB --memlimit-decompress=5MiB \
+ 		--no-adjust --threads=1 --check=crc32"
+ grep "define HAVE_CHECK_CRC64" ../config.h > /dev/null \
+ 		&& XZ="$XZ --check=crc64"
+ XZDEC="../src/xzdec/xzdec" # No memory usage limiter available
+ test -x ../src/xzdec/xzdec || XZDEC=
+ 
+ # Create the required input file if needed.
+ #
+ # Derive temporary filenames for compressed and uncompressed outputs
+ # from the input filename. This is needed when multiple tests are
+ # run in parallel.
+ FILE=$1
+ TMP_COMP="tmp_comp_$FILE"
+ TMP_UNCOMP="tmp_uncomp_$FILE"
+ 
+ case $FILE in
+ 	# compress_generated files will be created in the build directory
+ 	# in the /tests/ sub-directory.
+ 	compress_generated_*)
+ 		if ./create_compress_files "$FILE" ; then
+ 			:
+ 		else
+ 			rm -f "$FILE"
+ 			echo "Failed to create the file '$FILE'."
+ 			exit 1
+ 		fi
+ 		;;
+ 	# compress_prepared files exist in the source directory since they
+ 	# do not need to be copied or regenerated.
+ 	compress_prepared_*)
+ 		FILE="$srcdir/$FILE"
+ 		;;
+ 	'')
+ 		echo "No test file was specified."
+ 		exit 1
+ 		;;
+ esac
+ 
+ # Remove temporary now (in case they are something weird), and on exit.
+ rm -f "$TMP_COMP" "$TMP_UNCOMP"
+ trap 'rm -f "$TMP_COMP" "$TMP_UNCOMP"' 0
+ 
+ # Compress and decompress the file with various filter configurations.
+ #
+ # Don't test with empty arguments; it breaks some ancient
+ # proprietary /bin/sh versions due to $@ used in test_xz().
+ test_xz -1
+ test_xz -2
+ test_xz -3
+ test_xz -4
  
  test_filter()
  {
@@ -29,11 +158,57 @@ index 61d20ce9..0aa81001 100755
  	shift
  	test_xz "$@" --lzma2=dict=64KiB,nice=32,mode=fast
  }
+ 
+ test_filter DELTA --delta=dist=1
+ test_filter DELTA --delta=dist=4
+ test_filter DELTA --delta=dist=256
+ test_filter X86 --x86
+ test_filter POWERPC --power
+ test_filter IA64 --ia64
+ test_filter ARM --arm
+ test_filter ARMTHUMB --armthumb
+ test_filter SPARC --sparc
+ 
+ exit 0
 diff --git a/tests/test_files.sh b/tests/test_files.sh
 index 64d73081..e42af918 100755
 --- a/tests/test_files.sh
 +++ b/tests/test_files.sh
-@@ -35,7 +35,7 @@ fi
+@@ -1,197 +1,197 @@
+ #!/bin/sh
+ 
+ ###############################################################################
+ #
+ # Author: Lasse Collin
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ ###############################################################################
+ 
+ # If both xz and xzdec were not build, skip this test.
+ XZ=../src/xz/xz
+ XZDEC=../src/xzdec/xzdec
+ test -x "$XZ" || XZ=
+ test -x "$XZDEC" || XZDEC=
+ if test -z "$XZ$XZDEC"; then
+ 	echo "xz and xzdec were not built, skipping this test."
+ 	exit 77
+ fi
+ 
+ # If decompression support is missing, this test is skipped.
+ # This isn't perfect as if only some decompressors are disabled
+ # then some good files might not decompress and the test fails
+ # for a (kind of) wrong reason.
+ if grep 'define HAVE_DECODERS' ../config.h > /dev/null ; then
+ 	:
+ else
+ 	echo "Decompression support is disabled, skipping this test."
+ 	exit 77
+ fi
+ 
+ # If a feature was disabled at build time, make it possible to skip
+ # some of the test files. Use exit status 77 if any files were skipped.
  EXIT_STATUS=0
  have_feature()
  {
@@ -42,3 +217,159 @@ index 64d73081..e42af918 100755
  	printf '%s: Skipping because HAVE_%s is not enabled\n' "$2" "$1"
  	EXIT_STATUS=77
  	return 1
+ }
+ 
+ 
+ #######
+ # .xz #
+ #######
+ 
+ # If these integrity check types were disabled at build time,
+ # allow the tests to pass still.
+ NO_WARN=
+ grep 'define HAVE_CHECK_CRC64' ../config.h > /dev/null || NO_WARN=-qQ
+ grep 'define HAVE_CHECK_SHA256' ../config.h > /dev/null || NO_WARN=-qQ
+ 
+ for I in "$srcdir"/files/good-*.xz
+ do
+ 	# If features were disabled at build time, keep this still working.
+ 	case $I in
+ 		*/good-1-*delta-lzma2*.xz)
+ 			have_feature DECODER_DELTA "$I" || continue
+ 			;;
+ 	esac
+ 	case $I in
+ 		*/good-1-empty-bcj-lzma2.xz)
+ 			have_feature DECODER_POWERPC "$I" || continue
+ 			;;
+ 	esac
+ 	case $I in
+ 		*/good-1-sparc-lzma2.xz)
+ 			have_feature DECODER_SPARC "$I" || continue
+ 			;;
+ 	esac
+ 	case $I in
+ 		*/good-1-x86-lzma2.xz)
+ 			have_feature DECODER_X86 "$I" || continue
+ 			;;
+ 	esac
+ 	case $I in
+ 		*/good-1-arm64-lzma2-*.xz)
+ 			have_feature DECODER_ARM64 "$I" || continue
+ 			;;
+ 	esac
+ 
+ 	if test -z "$XZ" || "$XZ" $NO_WARN -dc "$I" > /dev/null; then
+ 		:
+ 	else
+ 		echo "Good file failed: $I"
+ 		exit 1
+ 	fi
+ 
+ 	if test -z "$XZDEC" || "$XZDEC" $NO_WARN "$I" > /dev/null; then
+ 		:
+ 	else
+ 		echo "Good file failed: $I"
+ 		exit 1
+ 	fi
+ done
+ 
+ for I in "$srcdir"/files/bad-*.xz
+ do
+ 	if test -n "$XZ" && "$XZ" -dc "$I" > /dev/null 2>&1; then
+ 		echo "Bad file succeeded: $I"
+ 		exit 1
+ 	fi
+ 
+ 	# xzdec doesn't warn about unsupported check so skip this if any of
+ 	# the check types were disabled at built time (NO_WARN isn't empty).
+ 	if test -n "$XZDEC" && test -z "$NO_WARN" \
+ 			&& "$XZDEC" "$I" > /dev/null 2>&1; then
+ 		echo "Bad file succeeded: $I"
+ 		exit 1
+ 	fi
+ done
+ 
+ # Testing for the lzma_index_append() bug in <= 5.2.6 needs "xz -l":
+ I="$srcdir/files/bad-3-index-uncomp-overflow.xz"
+ if test -n "$XZ" && "$XZ" -l "$I" > /dev/null 2>&1; then
+ 	echo "Bad file succeeded with xz -l: $I"
+ 	exit 1
+ fi
+ 
+ for I in "$srcdir"/files/unsupported-*.xz
+ do
+ 	# Test these only with xz as unsupported-check.xz will exit
+ 	# successfully with xzdec because it doesn't warn about
+ 	# unsupported check type.
+ 	if test -n "$XZ" && "$XZ" -dc "$I" > /dev/null 2>&1; then
+ 		echo "Unsupported file succeeded: $I"
+ 		exit 1
+ 	fi
+ done
+ 
+ # Test that this passes with --no-warn (-Q).
+ I="$srcdir/files/unsupported-check.xz"
+ if test -z "$XZ" || "$XZ" -dcqQ "$I" > /dev/null; then
+ 	:
+ else
+ 	echo "Unsupported file failed with xz -Q: $I"
+ 	exit 1
+ fi
+ 
+ if test -z "$XZDEC" || "$XZDEC" -qQ "$I" > /dev/null; then
+ 	:
+ else
+ 	echo "Unsupported file failed with xzdec -Q: $I"
+ 	exit 1
+ fi
+ 
+ 
+ #########
+ # .lzma #
+ #########
+ 
+ for I in "$srcdir"/files/good-*.lzma
+ do
+ 	if test -z "$XZ" || "$XZ" -dc "$I" > /dev/null; then
+ 		:
+ 	else
+ 		echo "Good file failed: $I"
+ 		exit 1
+ 	fi
+ done
+ 
+ for I in "$srcdir"/files/bad-*.lzma
+ do
+ 	if test -n "$XZ" && "$XZ" -dc "$I" > /dev/null 2>&1; then
+ 		echo "Bad file succeeded: $I"
+ 		exit 1
+ 	fi
+ done
+ 
+ 
+ #######
+ # .lz #
+ #######
+ 
+ if grep 'define HAVE_LZIP_DECODER' ../config.h > /dev/null ; then
+ 	for I in "$srcdir"/files/good-*.lz
+ 	do
+ 		if test -z "$XZ" || "$XZ" -dc "$I" > /dev/null; then
+ 			:
+ 		else
+ 			echo "Good file failed: $I"
+ 			exit 1
+ 		fi
+ 	done
+ 
+ 	for I in "$srcdir"/files/bad-*.lz "$srcdir"/files/unsupported-*.lz
+ 	do
+ 		if test -n "$XZ" && "$XZ" -dc "$I" > /dev/null 2>&1; then
+ 			echo "Bad file succeeded: $I"
+ 			exit 1
+ 		fi
+ 	done
+ fi
+ 
+ exit "$EXIT_STATUS"
diff --git a/affected_commits/xz/3a401b0e0c7a2658af7801dd0690256ef24149e0/patches/3a401b0e0c7a2658af7801dd0690256ef24149e0.diff b/affected_commits/xz/3a401b0e0c7a2658af7801dd0690256ef24149e0/patches/3a401b0e0c7a2658af7801dd0690256ef24149e0.diff
--- a/affected_commits/xz/3a401b0e0c7a2658af7801dd0690256ef24149e0/patches/3a401b0e0c7a2658af7801dd0690256ef24149e0.diff
+++ b/affected_commits/xz/3a401b0e0c7a2658af7801dd0690256ef24149e0/patches/3a401b0e0c7a2658af7801dd0690256ef24149e0.diff
@@ -8,7 +8,50 @@ diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
 index 25716873..19391ec4 100644
 --- a/.github/workflows/ci.yml
 +++ b/.github/workflows/ci.yml
-@@ -44,48 +44,55 @@ jobs:
+@@ -1,159 +1,185 @@
+ #############################################################################
+ #
+ # Author: Jia Tan
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ #############################################################################
+ 
+ name: CI
+ 
+ on:
+   # Triggers the workflow on push or pull request events but only for the master branch
+   push:
+     branches: [ master ]
+   pull_request:
+     branches: [ master ]
+ 
+   # Allows running workflow manually
+   workflow_dispatch:
+ 
+ jobs:
+   # When CMake can support disabling check types and
+   # encoders/decoders/threads, it will be combined to one Linux job
+   # and another matrix list.
+   Linux-Autotools:
+     # Just run on latest ubuntu
+     runs-on: ubuntu-latest
+     steps:
+       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+       - uses: actions/checkout@v2
+       - name: Install Dependencies
+         run: sudo apt-get install -y autoconf automake build-essential po4a autopoint gcc-multilib
+ 
+       # -b specifies the build system to use.
+       # -p specifies the phase (build or test) to help narrow down an error
+       #    if one occurs.
+       #
+       # Start with the 32-bit build because the autoconf cache must be reset
+       # after the build because the 32-bit build sets the CFLAGS env variable.
+       # By starting with the 32-bit build, we only have to clear the
+       # cache once.
+       - name: Build 32-bit
          run: ./build-aux/ci_build.sh -b autotools -p build -f "-m32"
        - name: Test 32-bit
          run: |
@@ -73,7 +116,11 @@ index 25716873..19391ec4 100644
  
    Linux-CMake:
      runs-on: ubuntu-latest
-@@ -97,6 +104,12 @@ jobs:
+     steps:
+       - uses: actions/checkout@v2
+       - name: Install Dependencies
+         run: sudo apt-get install -y build-essential cmake
+       - name: Build
          run: ./build-aux/ci_build.sh -b cmake -p build
        - name: Test
          run: ./build-aux/ci_build.sh -b cmake -p test
@@ -86,7 +133,12 @@ index 25716873..19391ec4 100644
  
    MacOS-Autotools:
      runs-on: macos-latest
-@@ -109,42 +122,49 @@ jobs:
+     steps:
+       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+       - uses: actions/checkout@v2
+       - name: Install Dependencies
+         run: brew install autoconf automake libtool po4a
+ 
        - name: Build with full features
          run: ./build-aux/ci_build.sh -b autotools -p build
        - name: Test with full features
@@ -144,7 +196,11 @@ index 25716873..19391ec4 100644
  
    MacOS-CMake:
      runs-on: macos-latest
-@@ -156,4 +176,10 @@ jobs:
+     steps:
+       - uses: actions/checkout@v2
+       - name: Install Dependencies
+         run: brew install cmake
+       - name: Build
          run: ./build-aux/ci_build.sh -b cmake -p build
        - name: Test
          run: ./build-aux/ci_build.sh -b cmake -p test
@@ -160,7 +216,26 @@ diff --git a/build-aux/ci_build.sh b/build-aux/ci_build.sh
 index 2d0f8643..85542c9b 100755
 --- a/build-aux/ci_build.sh
 +++ b/build-aux/ci_build.sh
-@@ -20,10 +20,11 @@ USAGE="Usage: $0
+@@ -1,187 +1,206 @@
+ #!/bin/sh
+ #
+ #############################################################################
+ #
+ # Script meant to be used for Continuous Integration automation for POSIX
+ # systems. On GitHub, this is used by Ubuntu and MacOS builds.
+ #
+ #############################################################################
+ #
+ # Author: Jia Tan
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ #############################################################################
+ 
+ set -e
+ 
+ USAGE="Usage: $0
    -b [autotools|cmake]
    -c [crc32|crc64|sha256]
    -d [encoders|decoders|bcj|delta|threads|shared|nls]
@@ -174,7 +249,17 @@ index 2d0f8643..85542c9b 100755
  
  # Absolute path of script directory
  ABS_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
-@@ -41,9 +42,10 @@ NATIVE_LANG_SUPPORT="y"
+ 
+ # Default CLI option values
+ BUILD_SYSTEM="autotools"
+ CHECK_TYPE="crc32,crc64,sha256"
+ BCJ="y"
+ DELTA="y"
+ ENCODERS="y"
+ DECODERS="y"
+ THREADS="y"
+ SHARED="y"
+ NATIVE_LANG_SUPPORT="y"
  SRC_DIR="$ABS_DIR/../"
  DEST_DIR="$SRC_DIR/../xz_build"
  PHASE="all"
@@ -186,7 +271,44 @@ index 2d0f8643..85542c9b 100755
  	# b option can have either value "autotools" OR "cmake"
  	case ${opt} in
  	h)
-@@ -88,6 +90,8 @@ while getopts b:c:d:l:s:p:f:h opt; do
+ 		echo "$USAGE"
+ 		exit 0
+ 	;;
+ 	b)
+ 		case "$OPTARG" in
+ 			autotools) ;;
+ 			cmake) ;;
+ 			*) echo "Invalid build system: $OPTARG"; exit 1;;
+ 		esac
+ 		BUILD_SYSTEM="$OPTARG"
+ 	;;
+ 	# c options can be a comma separated list of check types to support
+ 	c)
+ 	for crc in $(echo $OPTARG | sed "s/,/ /g"); do 
+ 		case "$crc" in
+ 		crc32) ;;
+ 		crc64) ;;
+ 		sha256) ;;
+ 		*) echo "Invalid check type: $crc"; exit 1 ;;
+ 		esac
+ 	done
+ 	CHECK_TYPE="$OPTARG"
+ 	;;
+ 	# d options can be a comma separated list of things to disable at
+ 	# configure time
+ 	d)
+ 	for disable_arg in $(echo $OPTARG | sed "s/,/ /g"); do 
+ 		case "$disable_arg" in
+ 		encoders) ENCODERS="n" ;;
+ 		decoders) DECODERS="n" ;;
+ 		bcj) BCJ="n" ;;
+ 		delta) DELTA="n" ;;
+ 		threads) THREADS="n" ;;
+ 		shared) SHARED="n";;
+ 		nls) NATIVE_LANG_SUPPORT="n";;
+ 		*) echo "Invalid disable value: $disable_arg"; exit 1 ;;
+ 		esac
+ 	done	
  	;;
  	l) DEST_DIR="$OPTARG"
  	;;
@@ -195,7 +317,89 @@ index 2d0f8643..85542c9b 100755
  	s) SRC_DIR="$OPTARG"
  	;;
  	p) PHASE="$OPTARG"
-@@ -177,11 +181,26 @@ if [ "$PHASE" = "all" ] || [ "$PHASE" = "test" ]; then
+ 	;;
+ 	f) 
+ 	CFLAGS="$OPTARG"
+ 	export CFLAGS
+ 	;;
+ 	esac
+ done
+ 
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "build" ]; then
+ 	# Build based on arguments
+ 	mkdir -p "$DEST_DIR"
+ 	case $BUILD_SYSTEM in
+ 		autotools)
+ 		cd "$SRC_DIR"
+ 
+ 		# Run autogen.sh script if not already run
+ 		if [ ! -f configure ]
+ 		then 
+ 			"./autogen.sh"
+ 		fi
+ 
+ 		cd "$DEST_DIR"
+ 
+ 		# Generate configure option values
+ 		EXTRA_OPTIONS=""
+ 		FILTER_LIST="lzma1,lzma2"
+ 
+ 		if [ "$BCJ" = "y" ]
+ 		then
+ 			FILTER_LIST="$FILTER_LIST,x86,powerpc,ia64,arm,armthumb,arm64,sparc"
+ 		fi
+ 
+ 		if [ "$DELTA" = "y" ]
+ 		then
+ 			FILTER_LIST="$FILTER_LIST,delta"
+ 		fi
+ 
+ 		if [ "$ENCODERS" = "y" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --enable-encoders=$FILTER_LIST"
+ 		else
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-encoders"
+ 		fi
+ 
+ 		if [ "$DECODERS" = "y" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --enable-decoders=$FILTER_LIST"
+ 		else
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-decoders"
+ 		fi
+ 
+ 		if [ "$THREADS" = "n" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-threads"
+ 		fi
+ 
+ 		if [ "$SHARED" = "n" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-shared"
+ 		fi
+ 
+ 		if [ "$NATIVE_LANG_SUPPORT" = "n" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-nls"
+ 		fi
+ 
+ 		# Run configure script
+ 		"$SRC_DIR"/configure --enable-werror --enable-checks=$CHECK_TYPE $EXTRA_OPTIONS --config-cache
+ 
+ 		# Build the project
+ 		make
+ 		;;
+ 		cmake)
+ 		# CMake currently does not support disabling encoders, decoders,
+ 		# threading, or check types. For now, just run the full build.
+ 		cd "$DEST_DIR"
+ 		cmake "$SRC_DIR/CMakeLists.txt" -B "$DEST_DIR"
+ 		make
+ 		;;
+ 	esac
+ fi
+ 
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "test" ]; then
  	case $BUILD_SYSTEM in
  		autotools)
  			cd "$DEST_DIR"
diff --git a/affected_commits/xz/4110a998b83459fe2bc9bc1bec30ad68afa8f797/patches/4110a998b83459fe2bc9bc1bec30ad68afa8f797.diff b/affected_commits/xz/4110a998b83459fe2bc9bc1bec30ad68afa8f797/patches/4110a998b83459fe2bc9bc1bec30ad68afa8f797.diff
--- a/affected_commits/xz/4110a998b83459fe2bc9bc1bec30ad68afa8f797/patches/4110a998b83459fe2bc9bc1bec30ad68afa8f797.diff
+++ b/affected_commits/xz/4110a998b83459fe2bc9bc1bec30ad68afa8f797/patches/4110a998b83459fe2bc9bc1bec30ad68afa8f797.diff
@@ -8,7 +8,25 @@ diff --git a/build-aux/ci_build.sh b/build-aux/ci_build.sh
 index 0e43d29f..e2c09cdb 100755
 --- a/build-aux/ci_build.sh
 +++ b/build-aux/ci_build.sh
-@@ -19,7 +19,7 @@ set -e
+@@ -1,180 +1,187 @@
+ #!/bin/sh
+ #
+ #############################################################################
+ #
+ # Script meant to be used for Continuous Integration automation for POSIX
+ # systems. On GitHub, this is used by Ubuntu and MacOS builds.
+ #
+ #############################################################################
+ #
+ # Author: Jia Tan
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ #############################################################################
+ 
+ set -e
+ 
  USAGE="Usage: $0
    -b [autotools|cmake]
    -c [crc32|crc64|sha256]
@@ -17,7 +35,17 @@ index 0e43d29f..e2c09cdb 100755
    -l [destdir]
    -s [srcdir]
    -p [all|build|test]
-@@ -37,6 +37,7 @@ ENCODERS="y"
+   -f [CFLAGS]"
+ 
+ # Absolute path of script directory
+ ABS_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
+ 
+ # Default CLI option values
+ BUILD_SYSTEM="autotools"
+ CHECK_TYPE="crc32,crc64,sha256"
+ BCJ="y"
+ DELTA="y"
+ ENCODERS="y"
  DECODERS="y"
  THREADS="y"
  SHARED="y"
@@ -25,7 +53,43 @@ index 0e43d29f..e2c09cdb 100755
  SRC_DIR="$ABS_DIR/../"
  DEST_DIR="$SRC_DIR/../xz_build"
  PHASE="all"
-@@ -80,6 +81,7 @@ while getopts b:c:d:l:s:p:f:h opt; do
+ 
+ # Parse arguments
+ while getopts b:c:d:l:s:p:f:h opt; do
+ 	# b option can have either value "autotools" OR "cmake"
+ 	case ${opt} in
+ 	h)
+ 		echo "$USAGE"
+ 		exit 0
+ 	;;
+ 	b)
+ 		case "$OPTARG" in
+ 			autotools) ;;
+ 			cmake) ;;
+ 			*) echo "Invalid build system: $OPTARG"; exit 1;;
+ 		esac
+ 		BUILD_SYSTEM="$OPTARG"
+ 	;;
+ 	# c options can be a comma separated list of check types to support
+ 	c)
+ 	for crc in $(echo $OPTARG | sed "s/,/ /g"); do 
+ 		case "$crc" in
+ 		crc32) ;;
+ 		crc64) ;;
+ 		sha256) ;;
+ 		*) echo "Invalid check type: $crc"; exit 1 ;;
+ 		esac
+ 	done
+ 	CHECK_TYPE="$OPTARG"
+ 	;;
+ 	# d options can be a comma separated list of things to disable at
+ 	# configure time
+ 	d)
+ 	for disable_arg in $(echo $OPTARG | sed "s/,/ /g"); do 
+ 		case "$disable_arg" in
+ 		encoders) ENCODERS="n" ;;
+ 		decoders) DECODERS="n" ;;
+ 		bcj) BCJ="n" ;;
  		delta) DELTA="n" ;;
  		threads) THREADS="n" ;;
  		shared) SHARED="n";;
@@ -33,7 +97,70 @@ index 0e43d29f..e2c09cdb 100755
  		*) echo "Invalid disable value: $disable_arg"; exit 1 ;;
  		esac
  	done	
-@@ -150,6 +152,11 @@ if [ "$PHASE" = "all" ] || [ "$PHASE" = "build" ]; then
+ 	;;
+ 	l) DEST_DIR="$OPTARG"
+ 	;;
+ 	s) SRC_DIR="$OPTARG"
+ 	;;
+ 	p) PHASE="$OPTARG"
+ 	;;
+ 	f) 
+ 	CFLAGS="$OPTARG"
+ 	export CFLAGS
+ 	;;
+ 	esac
+ done
+ 
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "build" ]; then
+ 	# Build based on arguments
+ 	mkdir -p "$DEST_DIR"
+ 	case $BUILD_SYSTEM in
+ 		autotools)
+ 		cd "$SRC_DIR"
+ 
+ 		# Run autogen.sh script if not already run
+ 		if [ ! -f configure ]
+ 		then 
+ 			"./autogen.sh"
+ 		fi
+ 
+ 		cd "$DEST_DIR"
+ 
+ 		# Generate configure option values
+ 		EXTRA_OPTIONS=""
+ 		FILTER_LIST="lzma1,lzma2"
+ 
+ 		if [ "$BCJ" = "y" ]
+ 		then
+ 			FILTER_LIST="$FILTER_LIST,x86,powerpc,ia64,arm,armthumb,arm64,sparc"
+ 		fi
+ 
+ 		if [ "$DELTA" = "y" ]
+ 		then
+ 			FILTER_LIST="$FILTER_LIST,delta"
+ 		fi
+ 
+ 		if [ "$ENCODERS" = "y" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --enable-encoders=$FILTER_LIST"
+ 		else
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-encoders"
+ 		fi
+ 
+ 		if [ "$DECODERS" = "y" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --enable-decoders=$FILTER_LIST"
+ 		else
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-decoders"
+ 		fi
+ 
+ 		if [ "$THREADS" = "n" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-threads"
+ 		fi
+ 
+ 		if [ "$SHARED" = "n" ]
+ 		then
  			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-shared"
  		fi
  
@@ -45,3 +172,29 @@ index 0e43d29f..e2c09cdb 100755
  		# Run configure script
  		"$SRC_DIR"/configure --enable-werror --enable-checks=$CHECK_TYPE $EXTRA_OPTIONS
  
+ 		# Build the project
+ 		make
+ 		;;
+ 		cmake)
+ 		# CMake currently does not support disabling encoders, decoders,
+ 		# threading, or check types. For now, just run the full build.
+ 		cd "$DEST_DIR"
+ 		cmake "$SRC_DIR/CMakeLists.txt" -B "$DEST_DIR"
+ 		make
+ 		;;
+ 	esac
+ fi
+ 
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "test" ]; then
+ 	case $BUILD_SYSTEM in
+ 		autotools)
+ 			cd "$DEST_DIR"
+ 			make check
+ 		;;
+ 		cmake)
+ 			cd "$DEST_DIR"
+ 			make "test"
+ 		;;
+ 	esac
+ fi
+\ No newline at end of file
diff --git a/affected_commits/xz/4de35fd6b58d46fc887c78faf163f6a37b790c45/patches/4de35fd6b58d46fc887c78faf163f6a37b790c45.diff b/affected_commits/xz/4de35fd6b58d46fc887c78faf163f6a37b790c45/patches/4de35fd6b58d46fc887c78faf163f6a37b790c45.diff
--- a/affected_commits/xz/4de35fd6b58d46fc887c78faf163f6a37b790c45/patches/4de35fd6b58d46fc887c78faf163f6a37b790c45.diff
+++ b/affected_commits/xz/4de35fd6b58d46fc887c78faf163f6a37b790c45/patches/4de35fd6b58d46fc887c78faf163f6a37b790c45.diff
@@ -12,7 +12,22 @@ diff --git a/build-aux/ci_build.sh b/build-aux/ci_build.sh
 index 76601580..85785d9f 100755
 --- a/build-aux/ci_build.sh
 +++ b/build-aux/ci_build.sh
-@@ -16,7 +16,7 @@
+@@ -1,141 +1,153 @@
+ #!/bin/sh
+ #
+ #############################################################################
+ #
+ # Script meant to be used for Continuous Integration automation for POSIX
+ # systems. On GitHub, this is used by Ubuntu and MacOS builds.
+ #
+ #############################################################################
+ #
+ # Author: Jia Tan
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ #############################################################################
  
  set -e
  
@@ -21,7 +36,14 @@ index 76601580..85785d9f 100755
  
  # Absolute path of script directory
  ABS_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
-@@ -31,9 +31,10 @@ DECODERS="y"
+ 
+ # Default CLI option values
+ BUILD_SYSTEM="autotools"
+ CHECK_TYPE="crc32,crc64,sha256"
+ BCJ="y"
+ DELTA="y"
+ ENCODERS="y"
+ DECODERS="y"
  THREADS="y"
  SRC_DIR="$ABS_DIR/../"
  DEST_DIR="$SRC_DIR/../xz_build"
@@ -33,7 +55,40 @@ index 76601580..85785d9f 100755
  	# b option can have either value "autotools" OR "cmake"
  	case ${opt} in
  	b)
-@@ -74,68 +75,79 @@ while getopts b:c:d:l:s: opt; do
+ 		case "$OPTARG" in
+ 			autotools) ;;
+ 			cmake) ;;
+ 			*) echo "Invalid build system: $OPTARG"; exit 1;;
+ 		esac
+ 		BUILD_SYSTEM="$OPTARG"
+ 	;;
+ 	# c options can be a comma separated list of check types to support
+ 	c)
+ 	for crc in $(echo $OPTARG | sed "s/,/ /g"); do 
+ 		case "$crc" in
+ 		crc32) ;;
+ 		crc64) ;;
+ 		sha256) ;;
+ 		*) echo "Invalid check type: $crc"; exit 1 ;;
+ 		esac
+ 	done
+ 	CHECK_TYPE="$OPTARG"
+ 	;;
+ 	# d options can be a comma separated list of things to disable at
+ 	# configure time
+ 	d)
+ 	for disable_arg in $(echo $OPTARG | sed "s/,/ /g"); do 
+ 		case "$disable_arg" in
+ 		encoders) ENCODERS="n" ;;
+ 		decoders) DECODERS="n" ;;
+ 		bcj) BCJ="n" ;;
+ 		delta) DELTA="n" ;;
+ 		threads) THREADS="n" ;;
+ 		*) echo "Invalid disable value: $disable_arg"; exit 1 ;;
+ 		esac
+ 	done	
+ 	;;
+ 	l) DEST_DIR="$OPTARG"
  	;;
  	s) SRC_DIR="$OPTARG"
  	;;
diff --git a/affected_commits/xz/4fabdb269f1fc5624b3b94a170c4efb329d1d229/patches/4fabdb269f1fc5624b3b94a170c4efb329d1d229.diff b/affected_commits/xz/4fabdb269f1fc5624b3b94a170c4efb329d1d229/patches/4fabdb269f1fc5624b3b94a170c4efb329d1d229.diff
--- a/affected_commits/xz/4fabdb269f1fc5624b3b94a170c4efb329d1d229/patches/4fabdb269f1fc5624b3b94a170c4efb329d1d229.diff
+++ b/affected_commits/xz/4fabdb269f1fc5624b3b94a170c4efb329d1d229/patches/4fabdb269f1fc5624b3b94a170c4efb329d1d229.diff
@@ -11,7 +11,50 @@ diff --git a/build-aux/ci_build.sh b/build-aux/ci_build.sh
 index 0a9dc09b..8edeb3c5 100755
 --- a/build-aux/ci_build.sh
 +++ b/build-aux/ci_build.sh
-@@ -44,7 +44,11 @@ DEST_DIR="$SRC_DIR/../xz_build"
+@@ -1,206 +1,259 @@
+ #!/bin/bash
+ #
+ #############################################################################
+ #
+ # Script meant to be used for Continuous Integration automation for POSIX
+ # systems. On GitHub, this is used by Ubuntu and MacOS builds.
+ #
+ #############################################################################
+ #
+ # Author: Jia Tan
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ #############################################################################
+ 
+ set -e
+ 
+ USAGE="Usage: $0
+   -b [autotools|cmake]
+   -c [crc32|crc64|sha256]
+   -d [encoders|decoders|bcj|delta|threads|shared|nls]
+   -f [CFLAGS]
+   -l [destdir]
+   -n [ARTIFACTS_DIR_NAME]
+   -p [all|build|test]
+   -s [srcdir]"
+ 
+ # Absolute path of script directory
+ ABS_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
+ 
+ # Default CLI option values
+ BUILD_SYSTEM="autotools"
+ CHECK_TYPE="crc32,crc64,sha256"
+ BCJ="y"
+ DELTA="y"
+ ENCODERS="y"
+ DECODERS="y"
+ THREADS="y"
+ SHARED="y"
+ NATIVE_LANG_SUPPORT="y"
+ SRC_DIR="$ABS_DIR/../"
+ DEST_DIR="$SRC_DIR/../xz_build"
  PHASE="all"
  ARTIFACTS_DIR_NAME="output"
  
@@ -24,7 +67,15 @@ index 0a9dc09b..8edeb3c5 100755
  while getopts b:c:d:l:n:s:p:f:h opt; do
  	# b option can have either value "autotools" OR "cmake"
  	case ${opt} in
-@@ -60,17 +64,7 @@ while getopts b:c:d:l:n:s:p:f:h opt; do
+ 	h)
+ 		echo "$USAGE"
+ 		exit 0
+ 	;;
+ 	b)
+ 		case "$OPTARG" in
+ 			autotools) ;;
+ 			cmake) ;;
+ 			*) echo "Invalid build system: $OPTARG"; exit 1;;
  		esac
  		BUILD_SYSTEM="$OPTARG"
  	;;
@@ -43,7 +94,15 @@ index 0a9dc09b..8edeb3c5 100755
  	;;
  	# d options can be a comma separated list of things to disable at
  	# configure time
-@@ -86,7 +80,7 @@ while getopts b:c:d:l:n:s:p:f:h opt; do
+ 	d)
+ 	for disable_arg in $(echo "$OPTARG" | sed "s/,/ /g"); do
+ 		case "$disable_arg" in
+ 		encoders) ENCODERS="n" ;;
+ 		decoders) DECODERS="n" ;;
+ 		bcj) BCJ="n" ;;
+ 		delta) DELTA="n" ;;
+ 		threads) THREADS="n" ;;
+ 		shared) SHARED="n";;
  		nls) NATIVE_LANG_SUPPORT="n";;
  		*) echo "Invalid disable value: $disable_arg"; exit 1 ;;
  		esac
@@ -52,7 +111,9 @@ index 0a9dc09b..8edeb3c5 100755
  	;;
  	l) DEST_DIR="$OPTARG"
  	;;
-@@ -96,111 +90,170 @@ while getopts b:c:d:l:n:s:p:f:h opt; do
+ 	n) ARTIFACTS_DIR_NAME="$OPTARG"
+ 	;;
+ 	s) SRC_DIR="$OPTARG"
  	;;
  	p) PHASE="$OPTARG"
  	;;
diff --git a/affected_commits/xz/52380678f42364daa4510f92f6d3b18ec98c3638/patches/52380678f42364daa4510f92f6d3b18ec98c3638.diff b/affected_commits/xz/52380678f42364daa4510f92f6d3b18ec98c3638/patches/52380678f42364daa4510f92f6d3b18ec98c3638.diff
--- a/affected_commits/xz/52380678f42364daa4510f92f6d3b18ec98c3638/patches/52380678f42364daa4510f92f6d3b18ec98c3638.diff
+++ b/affected_commits/xz/52380678f42364daa4510f92f6d3b18ec98c3638/patches/52380678f42364daa4510f92f6d3b18ec98c3638.diff
@@ -12,7 +12,30 @@ diff --git a/tests/create_compress_files.c b/tests/create_compress_files.c
 index 797a73e7..76aa3e30 100644
 --- a/tests/create_compress_files.c
 +++ b/tests/create_compress_files.c
-@@ -24,7 +24,7 @@
+@@ -1,163 +1,163 @@
+ ///////////////////////////////////////////////////////////////////////////////
+ //
+ /// \file       create_compress_files.c
+ /// \brief      Creates bunch of test files to be compressed
+ ///
+ /// Using a test file generator program saves space in the source code
+ /// package considerably.
+ //
+ //  Author:     Lasse Collin
+ //
+ //  This file has been put into the public domain.
+ //  You can do whatever you want with this file.
+ //
+ ///////////////////////////////////////////////////////////////////////////////
+ 
+ #include "sysdefs.h"
+ #include <stdio.h>
+ 
+ 
+ // If a command-line argument was given, only create the file if its
+ // name was specified on the command line. If no args were given then
+ // all files are created.
+ //
  // Avoid re-creating the test files every time the tests are run.
  #define maybe_create_test(argc, argv, name) \
  do { \
@@ -21,11 +44,228 @@ index 797a73e7..76aa3e30 100644
  			&& !file_exists("compress_generated_" #name)) { \
  		FILE *file = file_create("compress_generated_" #name); \
  		write_ ## name(file); \
+ 		file_finish(file, "compress_generated_" #name); \
+ 	} \
+ } while (0)
+ 
+ 
+ static bool
+ file_exists(const char *filename)
+ {
+ 	// Trying to be somewhat portable by avoiding stat().
+ 	FILE *file = fopen(filename, "rb");
+ 	bool ret;
+ 
+ 	if (file != NULL) {
+ 		fclose(file);
+ 		ret = true;
+ 	} else {
+ 		ret = false;
+ 	}
+ 
+ 	return ret;
+ }
+ 
+ 
+ static FILE *
+ file_create(const char *filename)
+ {
+ 	FILE *file = fopen(filename, "wb");
+ 
+ 	if (file == NULL) {
+ 		perror(filename);
+ 		exit(EXIT_FAILURE);
+ 	}
+ 
+ 	return file;
+ }
+ 
+ 
+ static void
+ file_finish(FILE *file, const char *filename)
+ {
+ 	const bool ferror_fail = ferror(file);
+ 	const bool fclose_fail = fclose(file);
+ 
+ 	if (ferror_fail || fclose_fail) {
+ 		perror(filename);
+ 		exit(EXIT_FAILURE);
+ 	}
+ }
+ 
+ 
+ // File that repeats "abc\n" a few thousand times. This is targeted
+ // especially at Subblock filter's run-length encoder.
+ static void
+ write_abc(FILE *file)
+ {
+ 	for (size_t i = 0; i < 12345; ++i)
+ 		if (fwrite("abc\n", 4, 1, file) != 1)
+ 			exit(EXIT_FAILURE);
+ }
+ 
+ 
+ // File that doesn't compress. We always use the same random seed to
+ // generate identical files on all systems.
+ static void
+ write_random(FILE *file)
+ {
+ 	uint32_t n = 5;
+ 
+ 	for (size_t i = 0; i < 123456; ++i) {
+ 		n = 101771 * n + 71777;
+ 
+ 		putc((uint8_t)(n), file);
+ 		putc((uint8_t)(n >> 8), file);
+ 		putc((uint8_t)(n >> 16), file);
+ 		putc((uint8_t)(n >> 24), file);
+ 	}
+ }
+ 
+ 
+ // Text file
+ static void
+ write_text(FILE *file)
+ {
+ 	static const char *lorem[] = {
+ 		"Lorem", "ipsum", "dolor", "sit", "amet,", "consectetur",
+ 		"adipisicing", "elit,", "sed", "do", "eiusmod", "tempor",
+ 		"incididunt", "ut", "labore", "et", "dolore", "magna",
+ 		"aliqua.", "Ut", "enim", "ad", "minim", "veniam,", "quis",
+ 		"nostrud", "exercitation", "ullamco", "laboris", "nisi",
+ 		"ut", "aliquip", "ex", "ea", "commodo", "consequat.",
+ 		"Duis", "aute", "irure", "dolor", "in", "reprehenderit",
+ 		"in", "voluptate", "velit", "esse", "cillum", "dolore",
+ 		"eu", "fugiat", "nulla", "pariatur.", "Excepteur", "sint",
+ 		"occaecat", "cupidatat", "non", "proident,", "sunt", "in",
+ 		"culpa", "qui", "officia", "deserunt", "mollit", "anim",
+ 		"id", "est", "laborum."
+ 	};
+ 
+ 	// Let the first paragraph be the original text.
+ 	for (size_t w = 0; w < ARRAY_SIZE(lorem); ++w) {
+ 		fprintf(file, "%s ", lorem[w]);
+ 
+ 		if (w % 7 == 6)
+ 			fprintf(file, "\n");
+ 	}
+ 
+ 	// The rest shall be (hopefully) meaningless combinations of
+ 	// the same words.
+ 	uint32_t n = 29;
+ 
+ 	for (size_t p = 0; p < 500; ++p) {
+ 		fprintf(file, "\n\n");
+ 
+ 		for (size_t w = 0; w < ARRAY_SIZE(lorem); ++w) {
+ 			n = 101771 * n + 71777;
+ 
+ 			fprintf(file, "%s ", lorem[n % ARRAY_SIZE(lorem)]);
+ 
+ 			if (w % 7 == 6)
+ 				fprintf(file, "\n");
+ 		}
+ 	}
+ }
+ 
+ 
+ int
+ main(int argc, char **argv)
+ {
+ 	maybe_create_test(argc, argv, abc);
+ 	maybe_create_test(argc, argv, random);
+ 	maybe_create_test(argc, argv, text);
+ 	return EXIT_SUCCESS;
+ }
 diff --git a/tests/test_compress.sh b/tests/test_compress.sh
 index 0692a8b1..361903a7 100755
 --- a/tests/test_compress.sh
 +++ b/tests/test_compress.sh
-@@ -85,9 +85,16 @@ test -x ../src/xzdec/xzdec || XZDEC=
+@@ -1,141 +1,147 @@
+ #!/bin/sh
+ 
+ ###############################################################################
+ #
+ # Author: Lasse Collin
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ ###############################################################################
+ 
+ # If xz wasn't built, this test is skipped.
+ if test -x ../src/xz/xz ; then
+ 	:
+ else
+ 	exit 77
+ fi
+ 
+ # If compression or decompression support is missing, this test is skipped.
+ # This isn't perfect as if only some compressors or decompressors are disabled
+ # then this script can still fail because for now this doesn't check the
+ # availability of each filter.
+ if grep 'define HAVE_ENCODERS' ../config.h > /dev/null \
+ 		&& grep 'define HAVE_DECODERS' ../config.h > /dev/null ; then
+ 	:
+ else
+ 	echo "Compression or decompression support is disabled, skipping this test."
+ 	exit 77
+ fi
+ 
+ # Find out if our shell supports functions.
+ eval 'unset foo ; foo() { return 42; } ; foo'
+ if test $? != 42 ; then
+ 	echo "/bin/sh doesn't support functions, skipping this test."
+ 	exit 77
+ fi
+ 
+ test_xz() {
+ 	if $XZ -c "$@" "$FILE" > "$TMP_COMP"; then
+ 		:
+ 	else
+ 		echo "Compressing failed: $* $FILE"
+ 		exit 1
+ 	fi
+ 
+ 	if $XZ -cd "$TMP_COMP" > "$TMP_UNCOMP" ; then
+ 		:
+ 	else
+ 		echo "Decompressing failed: $* $FILE"
+ 		exit 1
+ 	fi
+ 
+ 	if cmp "$TMP_UNCOMP" "$FILE" ; then
+ 		:
+ 	else
+ 		echo "Decompressed file does not match" \
+ 				"the original: $* $FILE"
+ 		exit 1
+ 	fi
+ 
+ 	if test -n "$XZDEC" ; then
+ 		if $XZDEC "$TMP_COMP" > "$TMP_UNCOMP" ; then
+ 			:
+ 		else
+ 			echo "Decompressing failed: $* $FILE"
+ 			exit 1
+ 		fi
+ 
+ 		if cmp "$TMP_UNCOMP" "$FILE" ; then
+ 			:
+ 		else
+ 			echo "Decompressed file does not match" \
+ 					"the original: $* $FILE"
+ 			exit 1
+ 		fi
+ 	fi
+ }
+ 
+ XZ="../src/xz/xz --memlimit-compress=48MiB --memlimit-decompress=5MiB \
+ 		--no-adjust --threads=1 --check=crc32"
+ grep "define HAVE_CHECK_CRC64" ../config.h > /dev/null \
+ 		&& XZ="$XZ --check=crc64"
+ XZDEC="../src/xzdec/xzdec" # No memory usage limiter available
+ test -x ../src/xzdec/xzdec || XZDEC=
  
  # Create the required input file if needed.
  FILE=$1
@@ -43,7 +283,7 @@ index 0692a8b1..361903a7 100755
  			:
  		else
  			rm -f "$FILE"
-@@ -95,18 +102,17 @@ case $FILE in
+ 			echo "Failed to create the file '$FILE'."
  			exit 1
  		fi
  		;;
@@ -67,6 +307,35 @@ index 0692a8b1..361903a7 100755
  # Remove temporary now (in case they are something weird), and on exit.
  rm -f "$TMP_COMP" "$TMP_UNCOMP"
  trap 'rm -f "$TMP_COMP" "$TMP_UNCOMP"' 0
+ 
+ # Compress and decompress the file with various filter configurations.
+ #
+ # Don't test with empty arguments; it breaks some ancient
+ # proprietary /bin/sh versions due to $@ used in test_xz().
+ test_xz -1
+ test_xz -2
+ test_xz -3
+ test_xz -4
+ 
+ test_filter()
+ {
+ 	grep "define HAVE_ENCODER_$1" ../config.h > /dev/null || return
+ 	grep "define HAVE_DECODER_$1" ../config.h > /dev/null || return
+ 	shift
+ 	test_xz "$@" --lzma2=dict=64KiB,nice=32,mode=fast
+ }
+ 
+ test_filter DELTA --delta=dist=1
+ test_filter DELTA --delta=dist=4
+ test_filter DELTA --delta=dist=256
+ test_filter X86 --x86
+ test_filter POWERPC --power
+ test_filter IA64 --ia64
+ test_filter ARM --arm
+ test_filter ARMTHUMB --armthumb
+ test_filter SPARC --sparc
+ 
+ exit 0
 diff --git a/tests/test_compress_prepared_bcj_sparc b/tests/test_compress_prepared_bcj_sparc
 index 01447e13..deb76ef6 100755
 --- a/tests/test_compress_prepared_bcj_sparc
diff --git a/affected_commits/xz/cf3d1f130e50cf63da4bb1031771605f6f443b6a/patches/cf3d1f130e50cf63da4bb1031771605f6f443b6a.diff b/affected_commits/xz/cf3d1f130e50cf63da4bb1031771605f6f443b6a/patches/cf3d1f130e50cf63da4bb1031771605f6f443b6a.diff
--- a/affected_commits/xz/cf3d1f130e50cf63da4bb1031771605f6f443b6a/patches/cf3d1f130e50cf63da4bb1031771605f6f443b6a.diff
+++ b/affected_commits/xz/cf3d1f130e50cf63da4bb1031771605f6f443b6a/patches/cf3d1f130e50cf63da4bb1031771605f6f443b6a.diff
@@ -14,9 +14,211 @@ diff --git a/build-aux/ci_build.sh b/build-aux/ci_build.sh
 index 3b462e63..0a9dc09b 100755
 --- a/build-aux/ci_build.sh
 +++ b/build-aux/ci_build.sh
-@@ -1,4 +1,4 @@
+@@ -1,206 +1,206 @@
 -#!/bin/sh
 +#!/bin/bash
  #
  #############################################################################
  #
+ # Script meant to be used for Continuous Integration automation for POSIX
+ # systems. On GitHub, this is used by Ubuntu and MacOS builds.
+ #
+ #############################################################################
+ #
+ # Author: Jia Tan
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ #############################################################################
+ 
+ set -e
+ 
+ USAGE="Usage: $0
+   -b [autotools|cmake]
+   -c [crc32|crc64|sha256]
+   -d [encoders|decoders|bcj|delta|threads|shared|nls]
+   -f [CFLAGS]
+   -l [destdir]
+   -n [ARTIFACTS_DIR_NAME]
+   -p [all|build|test]
+   -s [srcdir]"
+ 
+ # Absolute path of script directory
+ ABS_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
+ 
+ # Default CLI option values
+ BUILD_SYSTEM="autotools"
+ CHECK_TYPE="crc32,crc64,sha256"
+ BCJ="y"
+ DELTA="y"
+ ENCODERS="y"
+ DECODERS="y"
+ THREADS="y"
+ SHARED="y"
+ NATIVE_LANG_SUPPORT="y"
+ SRC_DIR="$ABS_DIR/../"
+ DEST_DIR="$SRC_DIR/../xz_build"
+ PHASE="all"
+ ARTIFACTS_DIR_NAME="output"
+ 
+ # Parse arguments
+ while getopts b:c:d:l:n:s:p:f:h opt; do
+ 	# b option can have either value "autotools" OR "cmake"
+ 	case ${opt} in
+ 	h)
+ 		echo "$USAGE"
+ 		exit 0
+ 	;;
+ 	b)
+ 		case "$OPTARG" in
+ 			autotools) ;;
+ 			cmake) ;;
+ 			*) echo "Invalid build system: $OPTARG"; exit 1;;
+ 		esac
+ 		BUILD_SYSTEM="$OPTARG"
+ 	;;
+ 	# c options can be a comma separated list of check types to support
+ 	c)
+ 	for crc in $(echo "$OPTARG" | sed "s/,/ /g"); do
+ 		case "$crc" in
+ 		crc32) ;;
+ 		crc64) ;;
+ 		sha256) ;;
+ 		*) echo "Invalid check type: $crc"; exit 1 ;;
+ 		esac
+ 	done
+ 	CHECK_TYPE="$OPTARG"
+ 	;;
+ 	# d options can be a comma separated list of things to disable at
+ 	# configure time
+ 	d)
+ 	for disable_arg in $(echo "$OPTARG" | sed "s/,/ /g"); do
+ 		case "$disable_arg" in
+ 		encoders) ENCODERS="n" ;;
+ 		decoders) DECODERS="n" ;;
+ 		bcj) BCJ="n" ;;
+ 		delta) DELTA="n" ;;
+ 		threads) THREADS="n" ;;
+ 		shared) SHARED="n";;
+ 		nls) NATIVE_LANG_SUPPORT="n";;
+ 		*) echo "Invalid disable value: $disable_arg"; exit 1 ;;
+ 		esac
+ 	done	
+ 	;;
+ 	l) DEST_DIR="$OPTARG"
+ 	;;
+ 	n) ARTIFACTS_DIR_NAME="$OPTARG"
+ 	;;
+ 	s) SRC_DIR="$OPTARG"
+ 	;;
+ 	p) PHASE="$OPTARG"
+ 	;;
+ 	f) 
+ 	CFLAGS="$OPTARG"
+ 	export CFLAGS
+ 	;;
+ 	esac
+ done
+ 
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "build" ]; then
+ 	# Build based on arguments
+ 	mkdir -p "$DEST_DIR"
+ 	case $BUILD_SYSTEM in
+ 		autotools)
+ 		cd "$SRC_DIR"
+ 
+ 		# Run autogen.sh script if not already run
+ 		if [ ! -f configure ]
+ 		then 
+ 			"./autogen.sh"
+ 		fi
+ 
+ 		cd "$DEST_DIR"
+ 
+ 		# Generate configure option values
+ 		EXTRA_OPTIONS=""
+ 		FILTER_LIST="lzma1,lzma2"
+ 
+ 		if [ "$BCJ" = "y" ]
+ 		then
+ 			FILTER_LIST="$FILTER_LIST,x86,powerpc,ia64,arm,armthumb,arm64,sparc"
+ 		fi
+ 
+ 		if [ "$DELTA" = "y" ]
+ 		then
+ 			FILTER_LIST="$FILTER_LIST,delta"
+ 		fi
+ 
+ 		if [ "$ENCODERS" = "y" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --enable-encoders=$FILTER_LIST"
+ 		else
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-encoders"
+ 		fi
+ 
+ 		if [ "$DECODERS" = "y" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --enable-decoders=$FILTER_LIST"
+ 		else
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-decoders"
+ 		fi
+ 
+ 		if [ "$THREADS" = "n" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-threads"
+ 		fi
+ 
+ 		if [ "$SHARED" = "n" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-shared"
+ 		fi
+ 
+ 		if [ "$NATIVE_LANG_SUPPORT" = "n" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-nls"
+ 		fi
+ 
+ 		# Run configure script
+ 		"$SRC_DIR"/configure --enable-werror --enable-checks="$CHECK_TYPE" $EXTRA_OPTIONS --config-cache
+ 
+ 		# Build the project
+ 		make
+ 		;;
+ 		cmake)
+ 		# CMake currently does not support disabling encoders, decoders,
+ 		# threading, or check types. For now, just run the full build.
+ 		cd "$DEST_DIR"
+ 		cmake "$SRC_DIR/CMakeLists.txt" -B "$DEST_DIR"
+ 		make
+ 		;;
+ 	esac
+ fi
+ 
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "test" ]; then
+ 	case $BUILD_SYSTEM in
+ 		autotools)
+ 			cd "$DEST_DIR"
+ 			# If the tests fail, copy the test logs into the artifacts folder
+ 			if make check
+ 			then
+ 				:
+ 			else
+ 				mkdir -p "$SRC_DIR/build-aux/artifacts/$ARTIFACTS_DIR_NAME"
+ 				cp ./tests/*.log "$SRC_DIR/build-aux/artifacts/$ARTIFACTS_DIR_NAME"
+ 				exit 1
+ 			fi
+ 		;;
+ 		cmake)
+ 			cd "$DEST_DIR"
+ 			if make test
+ 			then
+ 				:
+ 			else
+ 				mkdir -p "$SRC_DIR/build-aux/artifacts/$ARTIFACTS_DIR_NAME"
+ 				cp ./Testing/Temporary/*.log "$SRC_DIR/build-aux/artifacts/$ARTIFACTS_DIR_NAME"
+ 				exit 1
+ 			fi
+ 		;;
+ 	esac
+ fi
diff --git a/affected_commits/xz/d0faa85df5a5d253a4625d45313cf5e9277e6cd2/patches/d0faa85df5a5d253a4625d45313cf5e9277e6cd2.diff b/affected_commits/xz/d0faa85df5a5d253a4625d45313cf5e9277e6cd2/patches/d0faa85df5a5d253a4625d45313cf5e9277e6cd2.diff
--- a/affected_commits/xz/d0faa85df5a5d253a4625d45313cf5e9277e6cd2/patches/d0faa85df5a5d253a4625d45313cf5e9277e6cd2.diff
+++ b/affected_commits/xz/d0faa85df5a5d253a4625d45313cf5e9277e6cd2/patches/d0faa85df5a5d253a4625d45313cf5e9277e6cd2.diff
@@ -8,7 +8,95 @@ diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
 index 1691b5a8..823f5438 100644
 --- a/.github/workflows/ci.yml
 +++ b/.github/workflows/ci.yml
-@@ -89,12 +89,9 @@ jobs:
+@@ -1,125 +1,122 @@
+ #############################################################################
+ #
+ # Author: Jia Tan
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ #############################################################################
+ 
+ name: CI
+ 
+ on:
+   # Triggers the workflow on push or pull request events but only for the master branch
+   push:
+     branches: [ master ]
+   pull_request:
+     branches: [ master ]
+ 
+   # Allows running workflow manually
+   workflow_dispatch:
+ 
+ jobs:
+   POSIX:
+     strategy:
+       matrix:
+         os: [ubuntu-latest, macos-latest]
+         build_system: [autotools, cmake]
+     runs-on: ${{ matrix.os }}
+     steps:
+       - uses: actions/checkout@v2
+ 
+       ########################
+       # Install Dependencies #
+       ########################
+ 
+       # Install Autotools on Linux
+       - name: Install Dependencies
+         if: ${{ matrix.os == 'ubuntu-latest' && matrix.build_system == 'autotools' }}
+         run: sudo apt-get install -y autoconf automake build-essential po4a autopoint gcc-multilib doxygen
+ 
+       # Install Autotools on Mac
+       - name: Install Dependencies
+         if: ${{ matrix.os == 'macos-latest' && matrix.build_system == 'autotools' }}
+         run: brew install autoconf automake libtool po4a doxygen
+ 
+       # Install CMake on Linux
+       - name: Install Dependencies
+         if: ${{ matrix.os == 'ubuntu-latest' && matrix.build_system == 'cmake' }}
+         run: sudo apt-get install -y build-essential cmake
+ 
+       # Install CMake on Mac
+       - name: Install Dependencies
+         if: ${{ matrix.os == 'macos-latest' && matrix.build_system == 'cmake' }}
+         run: brew install cmake
+ 
+       ##################
+       # Build and Test #
+       ##################
+ 
+       # -b specifies the build system to use.
+       # -p specifies the phase (build or test) to help narrow down an error
+       #    if one occurs.
+       #
+       # Start with the 32-bit build because the autoconf cache must be reset
+       # after the build because the 32-bit build sets the CFLAGS env variable.
+       # By starting with the 32-bit build, we only have to clear the
+       # cache once. The 32-bit build is only tested on Autotools Linux.
+       - name: Build 32-bit
+         if: ${{ matrix.os == 'ubuntu-latest' && matrix.build_system == 'autotools' }}
+         run: ./build-aux/ci_build.sh -b autotools -p build -f "-m32"
+       - name: Test 32-bit
+         if: ${{ matrix.os == 'ubuntu-latest' && matrix.build_system == 'autotools' }}
+         run: |
+             ./build-aux/ci_build.sh -b autotools -p test -f "-m32" -n 32_bit
+             cd ../xz_build && make distclean
+ 
+       - name: Build with full features
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -p build
+       - name: Test with full features
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -p test -n full_features
+ 
+       - name: Build without encoders
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -d encoders,shared -p build
+       - name: Test without encoders
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -d encoders,shared -p test -n no_encoders
+ 
+       - name: Build without decoders
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -d decoders,shared -p build
        - name: Test without decoders
          run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -d decoders,shared -p test -n no_decoders
  
@@ -21,11 +109,237 @@ index 1691b5a8..823f5438 100644
          run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -d threads,shared -p test -n no_threads
  
        - name: Build without BCJ filters
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -d bcj,shared,nls -p build
+       - name: Test without BCJ filters
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -d bcj,shared,nls -p test -n no_bcj
+ 
+       - name: Build without Delta filters
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -d delta,shared,nls -p build
+       - name: Test without Delta filters
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -d delta,shared,nls -p test -n no_delta
+ 
+       - name: Build without sha256 check
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -c crc32,crc64 -d shared,nls -p build
+       - name: Test without sha256 check
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -c crc32,crc64 -d shared,nls -p test -n no_sha256
+ 
+       - name: Build without crc64 check
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -c crc32,sha256 -d shared,nls -p build
+       - name: Test without crc64 check
+         run: ./build-aux/ci_build.sh -b ${{ matrix.build_system }} -c crc32,sha256 -d shared,nls -p test -n no_crc64
+ 
+       # Attempt to upload the test logs as artifacts if any step has failed
+       - uses: actions/upload-artifact@v3
+         if: ${{ failure() }}
+         with:
+           name: ${{ matrix.os }} ${{ matrix.build_system }} Test Logs
+           path: build-aux/artifacts
 diff --git a/build-aux/ci_build.sh b/build-aux/ci_build.sh
 index 7fb180c2..724e66da 100755
 --- a/build-aux/ci_build.sh
 +++ b/build-aux/ci_build.sh
-@@ -202,13 +202,13 @@ then
+@@ -1,261 +1,261 @@
+ #!/bin/bash
+ #
+ #############################################################################
+ #
+ # Script meant to be used for Continuous Integration automation for POSIX
+ # systems. On GitHub, this is used by Ubuntu and MacOS builds.
+ #
+ #############################################################################
+ #
+ # Author: Jia Tan
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ #############################################################################
+ 
+ set -e
+ 
+ USAGE="Usage: $0
+   -b [autotools|cmake]
+   -c [crc32|crc64|sha256]
+   -d [encoders|decoders|bcj|delta|threads|shared|nls]
+   -f [CFLAGS]
+   -l [destdir]
+   -n [ARTIFACTS_DIR_NAME]
+   -p [all|build|test]
+   -s [srcdir]"
+ 
+ # Absolute path of script directory
+ ABS_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
+ 
+ # Default CLI option values
+ BUILD_SYSTEM="autotools"
+ CHECK_TYPE="crc32,crc64,sha256"
+ BCJ="y"
+ DELTA="y"
+ ENCODERS="y"
+ DECODERS="y"
+ THREADS="y"
+ SHARED="y"
+ NATIVE_LANG_SUPPORT="y"
+ SRC_DIR="$ABS_DIR/../"
+ DEST_DIR="$SRC_DIR/../xz_build"
+ PHASE="all"
+ ARTIFACTS_DIR_NAME="output"
+ 
+ 
+ ###################
+ # Parse arguments #
+ ###################
+ 
+ while getopts b:c:d:l:n:s:p:f:h opt; do
+ 	# b option can have either value "autotools" OR "cmake"
+ 	case ${opt} in
+ 	h)
+ 		echo "$USAGE"
+ 		exit 0
+ 	;;
+ 	b)
+ 		case "$OPTARG" in
+ 			autotools) ;;
+ 			cmake) ;;
+ 			*) echo "Invalid build system: $OPTARG"; exit 1;;
+ 		esac
+ 		BUILD_SYSTEM="$OPTARG"
+ 	;;
+ 	c) CHECK_TYPE="$OPTARG"
+ 	;;
+ 	# d options can be a comma separated list of things to disable at
+ 	# configure time
+ 	d)
+ 	for disable_arg in $(echo "$OPTARG" | sed "s/,/ /g"); do
+ 		case "$disable_arg" in
+ 		encoders) ENCODERS="n" ;;
+ 		decoders) DECODERS="n" ;;
+ 		bcj) BCJ="n" ;;
+ 		delta) DELTA="n" ;;
+ 		threads) THREADS="n" ;;
+ 		shared) SHARED="n";;
+ 		nls) NATIVE_LANG_SUPPORT="n";;
+ 		*) echo "Invalid disable value: $disable_arg"; exit 1 ;;
+ 		esac
+ 	done
+ 	;;
+ 	l) DEST_DIR="$OPTARG"
+ 	;;
+ 	n) ARTIFACTS_DIR_NAME="$OPTARG"
+ 	;;
+ 	s) SRC_DIR="$OPTARG"
+ 	;;
+ 	p) PHASE="$OPTARG"
+ 	;;
+ 	f)
+ 		CFLAGS="$OPTARG"
+ 		export CFLAGS
+ 	;;
+ 	esac
+ done
+ 
+ 
+ ####################
+ # Helper Functions #
+ ####################
+ 
+ # These two functions essentially implement the ternary "?" operator.
+ add_extra_option() {
+ 	# First argument is option value ("y" or "n")
+ 	# Second argument is option to set if "y"
+ 	# Third argument is option to set if "n"
+ 	if [ "$1" = "y" ]
+ 	then
+ 		EXTRA_OPTIONS="$EXTRA_OPTIONS $2"
+ 	else
+ 		EXTRA_OPTIONS="$EXTRA_OPTIONS $3"
+ 	fi
+ }
+ 
+ 
+ add_to_filter_list() {
+ 	# First argument is option value ("y" or "n")
+ 	# Second argument is option to set if "y"
+ 	if [ "$1" = "y" ]
+ 	then
+ 		FILTER_LIST="$FILTER_LIST$2"
+ 	fi
+ }
+ 
+ 
+ ###############
+ # Build Phase #
+ ###############
+ 
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "build" ]
+ then
+ 	# Checksum options should be specified differently based on the
+ 	# build system. It must be calculated here since we won't know
+ 	# the build system used until all args have been parsed.
+ 	# Autotools - comma separated
+ 	# CMake - semi-colon separated
+ 	if [ "$BUILD_SYSTEM" = "autotools" ]
+ 	then
+ 		SEP=","
+ 	else
+ 		SEP=";"
+ 	fi
+ 
+ 	CHECK_TYPE_TEMP=""
+ 	for crc in $(echo "$CHECK_TYPE" | sed "s/,/ /g"); do
+ 			case "$crc" in
+ 			# Remove "crc32" from cmake build, if specified.
+ 			crc32)
+ 				if [ "$BUILD_SYSTEM" = "cmake" ]
+ 				then
+ 					continue
+ 				fi
+ 			;;
+ 			crc64) ;;
+ 			sha256) ;;
+ 			*) echo "Invalid check type: $crc"; exit 1 ;;
+ 			esac
+ 
+ 			CHECK_TYPE_TEMP="$CHECK_TYPE_TEMP$SEP$crc"
+ 	done
+ 
+ 	# Remove the first character from $CHECK_TYPE_TEMP since it will
+ 	# always be the delimiter.
+ 	CHECK_TYPE="${CHECK_TYPE_TEMP:1}"
+ 
+ 	FILTER_LIST="lzma1$SEP"lzma2
+ 
+ 	# Build based on arguments
+ 	mkdir -p "$DEST_DIR"
+ 
+ 	# Generate configure option values
+ 	EXTRA_OPTIONS=""
+ 
+ 	case $BUILD_SYSTEM in
+ 	autotools)
+ 		cd "$SRC_DIR"
+ 
+ 		# Run autogen.sh script if not already run
+ 		if [ ! -f configure ]
+ 		then
+ 			"./autogen.sh"
+ 		fi
+ 
+ 		cd "$DEST_DIR"
+ 
+ 		add_to_filter_list "$BCJ" ",x86,powerpc,ia64,arm,armthumb,arm64,sparc"
+ 		add_to_filter_list "$DELTA" ",delta"
+ 
+ 		add_extra_option "$ENCODERS" "--enable-encoders=$FILTER_LIST" "--disable-encoders"
+ 		add_extra_option "$DECODERS" "--enable-decoders=$FILTER_LIST" "--disable-decoders"
+ 		add_extra_option "$THREADS" "" "--disable-threads"
+ 		add_extra_option "$SHARED" "" "--disable-shared"
+ 		add_extra_option "$NATIVE_LANG_SUPPORT" "" "--disable-nls"
+ 
+ 		# Run configure script
+ 		"$SRC_DIR"/configure --enable-werror --enable-checks="$CHECK_TYPE" $EXTRA_OPTIONS --config-cache
+ 
+ 		# Build the project
  		make
  	;;
  	cmake)
@@ -41,3 +355,50 @@ index 7fb180c2..724e66da 100755
  		# Disable MicroLZMA if encoders are not configured.
  		add_extra_option "$ENCODERS" "-DENCODERS=$FILTER_LIST" "-DENCODERS= -DMICROLZMA_ENCODER=OFF"
  
+ 		# Disable MicroLZMA and lzip decoders if decoders are not configured.
+ 		add_extra_option "$DECODERS" "-DDECODERS=$FILTER_LIST" "-DDECODERS= -DMICROLZMA_DECODER=OFF -DLZIP_DECODER=OFF"
+ 
+ 		# CMake disables the shared library by default.
+ 		add_extra_option "$SHARED" "-DBUILD_SHARED_LIBS=ON" ""
+ 
+ 		# Remove old cache file to clear previous settings.
+ 		rm -f "CMakeCache.txt"
+ 		cmake "$SRC_DIR/CMakeLists.txt" -B "$DEST_DIR" $EXTRA_OPTIONS -DADDITIONAL_CHECK_TYPES="$CHECK_TYPE"
+ 		make
+ 	;;
+ 	esac
+ fi
+ 
+ 
+ ##############
+ # Test Phase #
+ ##############
+ 
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "test" ]
+ then
+ 	case $BUILD_SYSTEM in
+ 	autotools)
+ 		cd "$DEST_DIR"
+ 		# If the tests fail, copy the test logs into the artifacts folder
+ 		if make check
+ 		then
+ 			:
+ 		else
+ 			mkdir -p "$SRC_DIR/build-aux/artifacts/$ARTIFACTS_DIR_NAME"
+ 			cp ./tests/*.log "$SRC_DIR/build-aux/artifacts/$ARTIFACTS_DIR_NAME"
+ 			exit 1
+ 		fi
+ 	;;
+ 	cmake)
+ 		cd "$DEST_DIR"
+ 		if make test
+ 		then
+ 			:
+ 		else
+ 			mkdir -p "$SRC_DIR/build-aux/artifacts/$ARTIFACTS_DIR_NAME"
+ 			cp ./Testing/Temporary/*.log "$SRC_DIR/build-aux/artifacts/$ARTIFACTS_DIR_NAME"
+ 			exit 1
+ 		fi
+ 	;;
+ 	esac
+ fi
diff --git a/affected_commits/xz/feae5528a30c006b6e2f96a95116e20b983703fc/patches/feae5528a30c006b6e2f96a95116e20b983703fc.diff b/affected_commits/xz/feae5528a30c006b6e2f96a95116e20b983703fc/patches/feae5528a30c006b6e2f96a95116e20b983703fc.diff
--- a/affected_commits/xz/feae5528a30c006b6e2f96a95116e20b983703fc/patches/feae5528a30c006b6e2f96a95116e20b983703fc.diff
+++ b/affected_commits/xz/feae5528a30c006b6e2f96a95116e20b983703fc/patches/feae5528a30c006b6e2f96a95116e20b983703fc.diff
@@ -11,7 +11,22 @@ diff --git a/build-aux/ci_build.sh b/build-aux/ci_build.sh
 index 85785d9f..8c309028 100755
 --- a/build-aux/ci_build.sh
 +++ b/build-aux/ci_build.sh
-@@ -16,7 +16,7 @@
+@@ -1,153 +1,157 @@
+ #!/bin/sh
+ #
+ #############################################################################
+ #
+ # Script meant to be used for Continuous Integration automation for POSIX
+ # systems. On GitHub, this is used by Ubuntu and MacOS builds.
+ #
+ #############################################################################
+ #
+ # Author: Jia Tan
+ #
+ # This file has been put into the public domain.
+ # You can do whatever you want with this file.
+ #
+ #############################################################################
  
  set -e
  
@@ -20,7 +35,17 @@ index 85785d9f..8c309028 100755
  
  # Absolute path of script directory
  ABS_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
-@@ -34,7 +34,7 @@ DEST_DIR="$SRC_DIR/../xz_build"
+ 
+ # Default CLI option values
+ BUILD_SYSTEM="autotools"
+ CHECK_TYPE="crc32,crc64,sha256"
+ BCJ="y"
+ DELTA="y"
+ ENCODERS="y"
+ DECODERS="y"
+ THREADS="y"
+ SRC_DIR="$ABS_DIR/../"
+ DEST_DIR="$SRC_DIR/../xz_build"
  PHASE="all"
  
  # Parse arguments
@@ -29,7 +54,42 @@ index 85785d9f..8c309028 100755
  	# b option can have either value "autotools" OR "cmake"
  	case ${opt} in
  	b)
-@@ -77,6 +77,10 @@ while getopts b:c:d:l:s:p: opt; do
+ 		case "$OPTARG" in
+ 			autotools) ;;
+ 			cmake) ;;
+ 			*) echo "Invalid build system: $OPTARG"; exit 1;;
+ 		esac
+ 		BUILD_SYSTEM="$OPTARG"
+ 	;;
+ 	# c options can be a comma separated list of check types to support
+ 	c)
+ 	for crc in $(echo $OPTARG | sed "s/,/ /g"); do 
+ 		case "$crc" in
+ 		crc32) ;;
+ 		crc64) ;;
+ 		sha256) ;;
+ 		*) echo "Invalid check type: $crc"; exit 1 ;;
+ 		esac
+ 	done
+ 	CHECK_TYPE="$OPTARG"
+ 	;;
+ 	# d options can be a comma separated list of things to disable at
+ 	# configure time
+ 	d)
+ 	for disable_arg in $(echo $OPTARG | sed "s/,/ /g"); do 
+ 		case "$disable_arg" in
+ 		encoders) ENCODERS="n" ;;
+ 		decoders) DECODERS="n" ;;
+ 		bcj) BCJ="n" ;;
+ 		delta) DELTA="n" ;;
+ 		threads) THREADS="n" ;;
+ 		*) echo "Invalid disable value: $disable_arg"; exit 1 ;;
+ 		esac
+ 	done	
+ 	;;
+ 	l) DEST_DIR="$OPTARG"
+ 	;;
+ 	s) SRC_DIR="$OPTARG"
  	;;
  	p) PHASE="$OPTARG"
  	;;
@@ -40,3 +100,75 @@ index 85785d9f..8c309028 100755
  	esac
  done
  
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "build" ]; then
+ 	# Build based on arguments
+ 	mkdir -p "$DEST_DIR"
+ 	case $BUILD_SYSTEM in
+ 		autotools)
+ 		# Run autogen.sh script
+ 		cd "$SRC_DIR"
+ 		"./autogen.sh"
+ 		cd "$DEST_DIR"
+ 		# Generate configure option values
+ 
+ 		EXTRA_OPTIONS=""
+ 		FILTER_LIST="lzma1,lzma2"
+ 
+ 		if [ "$BCJ" = "y" ]
+ 		then
+ 			FILTER_LIST="$FILTER_LIST,x86,powerpc,ia64,arm,armthumb,arm64,sparc"
+ 		fi
+ 
+ 		if [ "$DELTA" = "y" ]
+ 		then
+ 			FILTER_LIST="$FILTER_LIST,delta"
+ 		fi
+ 
+ 		if [ "$ENCODERS" = "y" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --enable-encoders=$FILTER_LIST"
+ 		else
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-encoders"
+ 		fi
+ 
+ 		if [ "$DECODERS" = "y" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --enable-decoders=$FILTER_LIST"
+ 		else
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-decoders"
+ 		fi
+ 
+ 		if [ "$THREADS" = "n" ]
+ 		then
+ 			EXTRA_OPTIONS="$EXTRA_OPTIONS --disable-threads"
+ 		fi
+ 
+ 		# Run configure script
+ 		"$SRC_DIR"/configure --enable-checks=$CHECK_TYPE $EXTRA_OPTIONS
+ 
+ 		# Build the project
+ 		make
+ 		;;
+ 		cmake)
+ 		# CMake currently does not support disabling encoders, decoders,
+ 		# threading, or check types. For now, just run the full build.
+ 		cd "$DEST_DIR"
+ 		cmake "$SRC_DIR/CMakeLists.txt" -B "$DEST_DIR"
+ 		make
+ 		;;
+ 	esac
+ fi
+ 
+ if [ "$PHASE" = "all" ] || [ "$PHASE" = "test" ]; then
+ 	case $BUILD_SYSTEM in
+ 		autotools)
+ 			cd "$DEST_DIR"
+ 			make check
+ 		;;
+ 		cmake)
+ 			cd "$DEST_DIR"
+ 			make "test"
+ 		;;
+ 	esac
+ fi
+\ No newline at end of file
